name: pyscenic_v2
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.7.3
  - apsw=3.34.0.r1
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bcrypt=3.2.0
  - bleach=3.3.0
  - boto3=1.17.5
  - botocore=1.20.5
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cachetools=4.2.1
  - certifi=2020.12.5
  - cffi=1.14.4
  - cgatcore=0.6.7
  - chardet=3.0.4
  - coreutils=8.25
  - cryptography=3.3.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - drmaa=0.7.9
  - entrypoints=0.3
  - expat=2.2.10
  - fontconfig=2.13.1
  - freetype=2.10.4
  - ftputil=4.0.0
  - gettext=0.19.8.1
  - gevent=21.1.2
  - glib=2.66.6
  - glib-tools=2.66.6
  - google-api-core=1.25.1
  - google-auth=1.24.0
  - google-cloud-core=1.5.0
  - google-cloud-sdk=327.0.0
  - google-cloud-storage=1.19.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.2.0
  - googleapis-common-protos=1.52.0
  - greenlet=0.4.17
  - grpcio=1.35.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - ipykernel=5.1.0
  - ipython=7.20.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jedi=0.18.0
  - jinja2=2.11.3
  - jmespath=0.10.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.11
  - jupyter_console=6.2.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.1
  - libev=4.33
  - libffi=3.3
  - libgcc=7.2.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.6
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libuv=1.40.0
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - multidict=5.1.0
  - nbclient=0.5.2
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - nomkl=1.0
  - notebook=6.2.0
  - numba=0.52.0
  - numpy=1.20.1
  - olefile=0.46
  - openssl=1.1.1i
  - packaging=20.9
  - pandoc=2.11.4
  - pandocfilters=1.4.2
  - paramiko=2.7.2
  - parso=0.8.1
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=21.0.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.14
  - prompt_toolkit=3.0.14
  - protobuf=3.14.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.7.4
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysftp=0.2.9
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2021.1
  - pyzmq=22.0.1
  - qt=5.9.7
  - qtconsole=5.0.2
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.25.1
  - rsa=4.7
  - ruffus=2.8.4
  - s3transfer=0.3.4
  - scipy=1.6.0
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - send2trash=1.5.0
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - sqlalchemy=1.3.23
  - sqlite=3.34.0
  - statsmodels=0.12.2
  - terminado=0.9.2
  - testpath=0.4.4
  - time=1.8
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - tzdata=2021a
  - urllib3=1.26.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.4.0
  - zlib=1.2.11
  - zope.event=4.5.0
  - zope.interface=5.2.0
  - zstd=1.4.8
  - pip:
    - arboreto==0.1.6
    - bokeh==2.2.3
    - boltons==20.2.1
    - cached-property==1.5.2
    - click==7.1.2
    - cloudpickle==1.6.0
    - dask==2021.2.0
    - dill==0.3.3
    - distributed==2021.2.0
    - frozendict==1.2
    - fsspec==0.8.5
    - h5py==3.1.0
    - heapdict==1.0.1
    - interlap==0.2.7
    - joblib==1.0.1
    - llvmlite==0.35.0
    - locket==0.2.1
    - loompy==3.0.6
    - msgpack==1.0.2
    - multiprocessing-on-dill==3.5.0a4
    - networkx==2.5
    - numpy-groupies==0.9.13
    - pandas==1.2.2
    - partd==1.1.0
    - psutil==5.8.0
    - pyarrow==0.16.0
    - pynndescent==0.5.2
    - pyscenic==0.11.0
    - pyyaml==5.4.1
    - scikit-learn==0.24.1
    - sortedcontainers==2.3.0
    - tblib==1.7.0
    - threadpoolctl==2.1.0
    - tqdm==4.56.1
    - umap-learn==0.5.1
    - zict==2.0.0
