name: renv
channels:
  - r
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.0
  - apsw=3.32.2.r1
  - bcrypt=3.2.0
  - binutils_impl_linux-64=2.35
  - binutils_linux-64=2.35
  - bioconductor-annotationdbi=1.52.0
  - bioconductor-biobase=2.50.0
  - bioconductor-biocgenerics=0.36.0
  - bioconductor-biocparallel=1.24.0
  - bioconductor-clusterprofiler=3.18.0
  - bioconductor-delayedarray=0.16.0
  - bioconductor-do.db=2.9
  - bioconductor-dose=3.16.0
  - bioconductor-enrichplot=1.10.0
  - bioconductor-fgsea=1.16.0
  - bioconductor-genomeinfodb=1.26.0
  - bioconductor-genomeinfodbdata=1.2.4
  - bioconductor-genomicranges=1.42.0
  - bioconductor-go.db=3.12.1
  - bioconductor-gosemsim=2.16.0
  - bioconductor-graph=1.68.0
  - bioconductor-graphite=1.36.0
  - bioconductor-iranges=2.24.0
  - bioconductor-mast=1.16.0
  - bioconductor-matrixgenerics=1.2.0
  - bioconductor-org.hs.eg.db=3.12.0
  - bioconductor-org.mm.eg.db=3.12.0
  - bioconductor-qvalue=2.22.0
  - bioconductor-reactome.db=1.74.0
  - bioconductor-reactomepa=1.34.0
  - bioconductor-s4vectors=0.28.0
  - bioconductor-singlecellexperiment=1.12.0
  - bioconductor-summarizedexperiment=1.20.0
  - bioconductor-xvector=0.30.0
  - bioconductor-zlibbioc=1.36.0
  - boto3=1.15.6
  - botocore=1.18.6
  - brotlipy=0.7.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.12.5
  - cachetools=4.1.1
  - cairo=1.16.0
  - certifi=2020.12.5
  - cffi=1.14.3
  - cgatcore=0.6.7
  - chardet=3.0.4
  - colormath=3.0.0
  - conda=4.9.2
  - conda-package-handling=1.7.2
  - coreutils=8.25
  - cryptography=3.1.1
  - curl=7.71.1
  - decorator=4.4.2
  - drmaa=0.7.9
  - fontconfig=2.13.1
  - freetype=2.10.2
  - fribidi=1.0.10
  - ftputil=4.0.0
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - gettext=0.19.8.1
  - gevent=20.9.0
  - gfortran_impl_linux-64=7.5.0
  - gfortran_linux-64=7.5.0
  - glib=2.66.0
  - gmp=6.2.0
  - google-api-core=1.22.2
  - google-auth=1.21.2
  - google-cloud-core=1.4.1
  - google-cloud-sdk=311.0.0
  - google-cloud-storage=1.31.0
  - google-crc32c=1.0.0
  - google-resumable-media=1.0.0
  - googleapis-common-protos=1.51.0
  - graphite2=1.3.13
  - greenlet=0.4.17
  - grpcio=1.31.0
  - gsl=2.6
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - harfbuzz=2.7.2
  - icu=67.1
  - idna=2.10
  - jmespath=0.10.0
  - jpeg=9d
  - kernel-headers_linux-64=2.6.32
  - krb5=1.17.1
  - ld_impl_linux-64=2.35
  - libarchive=3.5.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcrc32c=1.1.1
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-devel_linux-64=7.5.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libprotobuf=3.13.0
  - libsolv=0.7.17
  - libssh2=1.9.0
  - libstdcxx-devel_linux-64=7.5.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - lzo=2.10
  - make=4.3
  - mamba=0.7.10
  - ncurses=6.2
  - networkx=2.5
  - nomkl=1.0
  - numpy=1.19.1
  - openssl=1.1.1i
  - pandas=1.1.2
  - pandoc=2.10.1
  - pango=1.42.4
  - paramiko=2.7.2
  - pcre=8.44
  - pcre2=10.35
  - pip=20.2.3
  - pixman=0.38.0
  - protobuf=3.13.0
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycosat=0.6.3
  - pycparser=2.20
  - pynacl=1.3.0
  - pyopenssl=19.1.0
  - pysftp=0.2.9
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyyaml=5.3.1
  - r=4.0
  - r-abind=1.4_5
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.1.10
  - r-base=4.0.2
  - r-base64enc=0.1_3
  - r-bh=1.72.0_3
  - r-biocmanager=1.30.10
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-bitops=1.0_6
  - r-blob=1.2.1
  - r-boot=1.3_25
  - r-broom=0.7.0
  - r-callr=3.4.4
  - r-catools=1.18.0
  - r-cellranger=1.1.0
  - r-checkmate=2.0.0
  - r-class=7.3_17
  - r-cli=2.0.2
  - r-clipr=0.7.0
  - r-cluster=2.1.0
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-commonmark=1.7
  - r-cowplot=1.1.0
  - r-crayon=1.3.4
  - r-crosstalk=1.1.0.1
  - r-curl=4.3
  - r-data.table=1.12.8
  - r-dbi=1.1.0
  - r-dbplyr=1.4.4
  - r-deldir=0.1_29
  - r-desc=1.2.0
  - r-digest=0.6.25
  - r-domc=1.3.6
  - r-downloader=0.4
  - r-dplyr=1.0.2
  - r-dqrng=0.2.1
  - r-ellipsis=0.3.1
  - r-europepmc=0.4
  - r-evaluate=0.14
  - r-fansi=0.4.1
  - r-farver=2.0.3
  - r-fastmap=1.0.1
  - r-fastmatch=1.1_0
  - r-fitdistrplus=1.1_1
  - r-fnn=1.1.3
  - r-forcats=0.5.0
  - r-foreach=1.5.0
  - r-foreign=0.8_80
  - r-formatr=1.7
  - r-fs=1.5.0
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.19.1
  - r-future.apply=1.6.0
  - r-gdata=2.18.0
  - r-generics=0.0.2
  - r-ggforce=0.3.2
  - r-ggplot2=3.3.2
  - r-ggplotify=0.0.5
  - r-ggraph=2.0.3
  - r-ggrepel=0.8.2
  - r-ggridges=0.5.2
  - r-globals=0.13.0
  - r-glue=1.4.2
  - r-goftest=1.2_2
  - r-gplots=3.1.0
  - r-graphlayouts=0.7.0
  - r-gridextra=2.3
  - r-gridgraphics=0.5_0
  - r-gtable=0.3.0
  - r-gtools=3.8.2
  - r-haven=2.3.1
  - r-hexbin=1.28.1
  - r-highr=0.8
  - r-hms=0.5.3
  - r-htmltools=0.5.0
  - r-htmlwidgets=1.5.1
  - r-httpuv=1.5.4
  - r-httr=1.4.2
  - r-ica=1.0_2
  - r-igraph=1.2.5
  - r-irlba=2.3.3
  - r-isoband=0.2.2
  - r-iterators=1.0.12
  - r-jsonlite=1.7.1
  - r-kernsmooth=2.23_17
  - r-knitr=1.30
  - r-labeling=0.3
  - r-lambda.r=1.2.4
  - r-later=1.1.0.1
  - r-lattice=0.20_41
  - r-lazyeval=0.2.2
  - r-leiden=0.3.3
  - r-lifecycle=0.2.0
  - r-listenv=0.8.0
  - r-lmtest=0.9_38
  - r-lsei=1.3_0
  - r-lubridate=1.7.9
  - r-magrittr=1.5
  - r-markdown=1.1
  - r-mass=7.3_53
  - r-matrix=1.2_18
  - r-matrixstats=0.57.0
  - r-memoise=1.1.0
  - r-mgcv=1.8_33
  - r-mime=0.9
  - r-miniui=0.1.1.1
  - r-modelr=0.1.8
  - r-msigdbr=7.1.1
  - r-munsell=0.5.0
  - r-nlme=3.1_149
  - r-nnet=7.3_14
  - r-npsurv=0.5_0
  - r-openssl=1.4.3
  - r-patchwork=1.0.1
  - r-pbapply=1.4_3
  - r-pheatmap=1.0.12
  - r-pillar=1.4.6
  - r-pkgbuild=1.1.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.1.0
  - r-plogr=0.2.0
  - r-plotly=4.9.2.1
  - r-plyr=1.8.6
  - r-png=0.1_7
  - r-polyclip=1.10_0
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.4.4
  - r-progress=1.2.2
  - r-promises=1.1.1
  - r-ps=1.3.4
  - r-purrr=0.3.4
  - r-r6=2.4.1
  - r-rann=2.6.1
  - r-rappdirs=0.3.1
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.4.6
  - r-rcppannoy=0.0.16
  - r-rcpparmadillo=0.9.900.3.0
  - r-rcppeigen=0.3.3.7.0
  - r-rcppparallel=5.0.2
  - r-rcppprogress=0.4.2
  - r-rcurl=1.98_1.2
  - r-readr=1.3.1
  - r-readxl=1.3.1
  - r-recommended=4.0
  - r-rematch=1.0.1
  - r-reprex=0.3.0
  - r-reshape2=1.4.4
  - r-reticulate=1.16
  - r-rlang=0.4.7
  - r-rmarkdown=2.3
  - r-rocr=1.0_11
  - r-rpart=4.1_15
  - r-rprojroot=1.3_2
  - r-rspectra=0.16_0
  - r-rsqlite=2.2.0
  - r-rstudioapi=0.11
  - r-rsvd=1.0.3
  - r-rtsne=0.15
  - r-rvcheck=0.1.8
  - r-rvest=0.3.6
  - r-scales=1.1.1
  - r-scattermore=0.7
  - r-scatterpie=0.1.5
  - r-sctransform=0.3.2
  - r-selectr=0.4_2
  - r-seurat=3.2.3
  - r-shadowtext=0.0.7
  - r-shiny=1.5.0
  - r-sitmo=2.0.1
  - r-snow=0.4_3
  - r-sourcetools=0.1.7
  - r-spatial=7.3_12
  - r-spatstat=1.64_1
  - r-spatstat.data=1.4_3
  - r-spatstat.utils=1.17_0
  - r-stringi=1.5.3
  - r-stringr=1.4.0
  - r-survival=3.2_3
  - r-sys=3.4
  - r-tensor=1.5
  - r-testthat=2.3.2
  - r-tibble=3.0.3
  - r-tidygraph=1.2.0
  - r-tidyr=1.1.2
  - r-tidyselect=1.1.0
  - r-tidyverse=1.3.0
  - r-tinytex=0.26
  - r-triebeard=0.3.0
  - r-tweenr=1.0.1
  - r-urltools=1.7.3
  - r-utf8=1.1.4
  - r-uwot=0.1.10
  - r-vctrs=0.3.4
  - r-viridis=0.5.1
  - r-viridislite=0.3.0
  - r-whisker=0.4
  - r-withr=2.3.0
  - r-xfun=0.17
  - r-xml2=1.3.2
  - r-xtable=1.8_4
  - r-yaml=2.2.1
  - r-zeallot=0.1.0
  - r-zoo=1.8_8
  - readline=8.0
  - reproc=14.2.1
  - reproc-cpp=14.2.1
  - requests=2.24.0
  - rsa=4.6
  - ruamel_yaml=0.15.80
  - ruffus=2.8.4
  - s3transfer=0.3.3
  - sed=4.8
  - setuptools=49.6.0
  - six=1.15.0
  - spectra=0.0.11
  - sqlalchemy=1.3.19
  - sqlite=3.33.0
  - sysroot_linux-64=2.12
  - time=1.8
  - tk=8.6.10
  - tktable=2.10
  - tqdm=4.56.0
  - urllib3=1.25.10
  - wheel=0.35.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zope.event=4.5.0
  - zope.interface=5.1.0
  - zstd=1.4.5
