# YAML file for pipeline_pyscenic_downstream.py

cluster:
    queue: batchq

datatype: raw   # can be raw or normalised

aucell:
    tab: -t     # include -t if gene expression matrix is csv file (genes as rows, cells as columns)
    threads: 5     # 15

regulons:
    threads: 5    # 15

binarize:
    tab: -t     # include -t if gene expression matrix is csv file (genes as rows, cells as columns)
    custom_aucell_thresholds: # data.dir/custom_aucell_thresholds.csv      # optional path to custom AUCell thresholds file
    threads: 20    # max is 20

rss_zscore:
    annotation_files: data.dir/GI2792_graft_donorcells_annotation.csv
    tab: -t      # include -t if gene expression matrix is csv file (genes as rows, cells as columns)
    threads: 5
