# YAML file for pipeline_pyscenic_r.py

cluster:
    queue: all.q
conda_env: python3-env
#datatype: raw    # can be raw or normalised
working_dir: /ifs/research-groups/cncb/proj021/analyses/Pyscenic_glia/scenic
results_directory: pyscenic_results.dir/pyscenic_r
plots_directory: plots.dir/pyscenic_r
binary_matrix: binary_matrix.csv
aucell_scores: Thirst2Glia_aucell.csv
aucell_zscores: aucell_zscores.csv
aucell_zscores_celltype: aucell_zscores_Glia_celltype_ann_annotations.csv
aucell_zscores_condition: aucell_zscores_Glia_condition_annotations.csv
rseurat:
    threads: 15
    seurat_object: Robjects/Thirst2_TrimPlus_Glia.rds
    umap_pcs: 8    # how many PCs to use for clustering on AUCell scores
    cell_type: celltype_ann
    condition: stim
    clustering_resolution: 0.8
    stacked_vln_function: R/stacked_violin.R
    reference_condition: sat00
    FDR_threshold: 0.01   # FDR threshold for top 10 wilcoxon heatmap

rscenic:
    num_workers: 15 # Number of cores
    datatype: raw # raw or normalised
    celltype: celltype_ann # column name for cell celltype annotations in files or "None"
    condition: stim # column name for condition annotation in files or "None"
    celltype_condition: celltype_stim # column name for celltype_condition columns in files or "None"
    celltype_stim_zscores: aucell_zscores_Glia_celltype_stim_annotations.csv  # Zscores based on auc for celltype_stim joint or "None"
    celltype_zscore_filter_threshold: 2 # Zscore filter threshold for celltype specific scores for heatmap or "None"
    stim_zscore_filter_threshold: 1 # Zscore filter threshold for  condition specific scores for heatmap or "None"
    celltype_stim_zscore_filter_threshold: 2 # Zscore filter threshold for  celltype + condition specific  scores for heatmap or "None"
    annotation_celltype: data.dir/Glia_celltype_ann_annotations.csv # csv file with cellid & celltype annotations for each cell or "None"
    annotation_stim: data.dir/Glia_condition_annotations.csv # csv file with cellid & stim annotation  for each cell or "None"
    annotation_celltype_stim: data.dir/Glia_celltype_stim_annotations.csv #csv file with cellid & celltype_stim annotation for each cell or "None"
    binary_heatmap_cell_annotations : data.dir/Glia_celltype_ann_annotations.csv  # csv file with cellid and annotation data per cell for binary all cells heatmap or "None"
    rss_celltype: Glia_celltype_ann_annotations_RSS.csv # RSS scores per regulon for celltype or "None"
    rss_stim: Glia_condition_annotations_RSS.csv # RSS scores per regulon for stim or "None"
    rss_celltype_stim: Glia_celltype_stim_annotations_RSS.csv # RSS scores per regulon for celltype_stim or "None"
    species: fly # fly ;human ,mouse or None
    regulon_genes: regulons.csv #regulon files generatated from Pyscenic pipeline or "None"
    exp_matrix: Thirst2Glia_filtered-expression.csv # *_filtered-expression.csv exp matrix generated in step1 of pipeline for background for pathway analysis or "None"
    go_ont_option: BP # "BP", "MF" , "CC" or "ALL" for all three. Default is "MF" in ClusterProfiler
    wilcoxon_celltype_top: wilcoxon_celltype_top10.csv #or "None"
    wilcoxon_condition_top: wilcoxon_condition_top10.csv # or "None"
    ks_celltype_top: ks_celltype_top10.csv # or "None"
    ks_condition_top: ks_condition_top10.csv # or "None"
    pvaluecutoff: 0.05 # Pathway enrichment cutoffs
    qvaluecutoff: 0.05 # Pathway enrichment cutoffs
    maxGSSize: 1000 # Pathway enrichment maximum gneset size
    msigdb_geneset: C2 # geneset category for MSigDB, can be C1: positional gene sets ,C2: curated gene sets,C3: motif gene sets,C4: computational gene sets, C5: GO gene sets,C6: oncogenic signatures,C7: immunologic signatures,H: hallmark gene sets
