# YAML file for pyscenic_pipeline.py

cluster:
    queue: all.q

conda_env: pyscenic_2    

filtering:
    threads: 2
    input_format: csv     # either h5ad or csv
    UMI_counts: 3
    min_percent: 0.01
    other_options: # --downsample --cell_number 200000     # only use for h5ad file format

grn:
    threads: 5   # 18
    tfs_list: resources.dir/allTFs_dmel.txt
    other_options: -t    # add -t if csv file is genes (rows) x cells (columns)

add_cor:
        threads: 5
        other_options: -t  # add -t if csv file is genes (rows) x cells (columns)

ctx:
    threads: 5   # 10
    annotations: resources.dir/motifs-v8-nr.flybase-m0.001-o0.0.tbl
    # the name of the file that contains the motif annotations to use
    database_fname:
        - resources.dir/dm6-5kb-upstream-full-tx-11species.mc8nr.feather
        -     # this can be left empty
    # the name(s) of the regulatory feature databases; two file formats are supported: feather or db (legacy)
    other_options: -t     # --mask_dropouts, add -t if csv file is genes (rows) x cells (columns)

aucell:
    threads: 5   # 18
    auc_threshold: 0.05
    other_options: -t     # add -t if csv file is genes (rows) x cells (columns)
